package:
  name: pytexshade
  version: "0.0.1"

source:
  git_url: git@github.com:intbio/pytexshade
#  patches:
   # List any patch files here
   # - fix.patch

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - biopython 
    - tectonic
    - imagemagick
    - ghostscript
    
  run:
    - python
    - setuptools
    - biopython 
    - tectonic
    - imagemagick
    - ghostscript

test:
  # Python imports
  imports:
    - pytexshade

  # commands:
    # python example.py
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/intbio/pytexshade
  license: GPL3.0
  summary: 'A python wrapper for TexShade sequence alignment shader'
  license_family: GPL

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
